### PR TITLE
RN-02 Signup/Signin Components

### PR DESCRIPTION
**Pull request by samwalker191**
I ended up adding the signin component into this as well since they are kind of both on the same page. Functionality is not fully there until the backend app is live. It might be worth breaking that into its own issue?

Can we set urls for the ajax calls to just go to localhost and run the server for ourselves? Once the backend up is hosted somewhere we would just need to update the urls.

### CODE REVIEW

**Comment by samwalker191** [comment]
I gotta update this to work with Liz's update. Lemme do that then it can be reviewed.

**Comment by samwalker191** [comment]
I've updated the styling, but am having issues trying to get this to work with the changes to main branch. When working on my branch I can test the app on android and ios phones, but not on the web browser via expo. When I had rebased with the main branch, it sort of worked in the web browser via expo, but no longer worked on the phones. 

I've tried to see what are the differences, looking at settings and stuff like that but cant find out why it is not working.

**Comment by ghost** [comment]
I'll take a look at it tomorrow morning and see if I can find any fixes.  @samwalker191

**Comment by samwalker191** [comment]
Aiiight, I just rebased again and messed with a few things. It seems to be working with the main branch now. However, it is still only working with the web browser view in expo. Running it on the phone doesn't seem to work, and not entirely sure why.

You can look at the session forms by hitting the calendar icon on the home page.

And thank you Carlos!

**Comment by samwalker191** [comment]
Ok, it now seems to work with phones. I made some changes to styling that already exists. It shouldnt change the result, just formatted it to work with phone expo. 

The original error I had before is not happening anymore, so I'm just gonna go with it lol.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
looks like everything is running well ! the only thing is that on my i phone I don't have the bottom bar that allows me to go to the signup page with the links.  But on the web browser is does show up

**Pull request merged**
